sudo: required
language: node_js
node_js:
  - 4.4.5
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get -qq update
  - sudo apt-get install -y graphicsmagick yarn=0.18.1-1
cache:
  directories:
  - $HOME/.cache/yarn
