version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.13.2-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo npm install -g bower grunt-cli gulp-cli npm@8
            sudo apt-get update -qq
            sudo apt-get install -y -qq graphicsmagick
            npm ci
      - run:
          name: Run tests
          command: npm test
